# $NetBSD$
#

DISTNAME=	MPlayer-1.0rc4
CATEGORIES=	multimedia
MASTER_SITES=	http://www1.mplayerhq.hu/MPlayer/releases/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	http://www1.mplayerhq.hu/MPlayer/releases/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
