# $NetBSD: Makefile,v 1.878 2012/03/22 14:53:57 taca Exp $
#

COMMENT=	Packages related to the World Wide Web

SUBDIR+=	apache22
SUBDIR+=	cherokee
SUBDIR+=	curl
SUBDIR+=	libwww
SUBDIR+=	neon

.include "../mk/misc/category.mk"
